### ISSUE TITLE
lib-B mESCs dataset

### ISSUE THREAD

**Issue by krejciadam** [gifford-lab/inDelphi-dataprocessinganalysis#1]
Hello! 

I tried to download fully processed data from figshare, but it seems some datasets are missing, or maybe I'm just unable to decode file names used for the figshare files. Specifically, I'm after the dataset of lib-B in mESCs without any knockout or inhibitor treatment, i.e. the datasets behind this part of the article: 

> We selected 1,592 pathogenic human loci with high predicted rates of frame correction or microduplication correction to the wild-type sequence for inclusion in a second library (lib-B). We observed that 183 human disease microduplication alleles included in lib-B were repaired to wild-type in ≥50% of all products (Fig. 4b), and 508 path- ogenic human frameshift alleles were corrected into proper reading frames in ≥50% of all products in mESCs (Fig. 4c), in agreement with inDelphi’s predictions (r = 0.64 and 0.64).

I thought I would find the dataset in this figshare folder: 
[https://figshare.com/articles/inDelphi-LibA_LibB-processed-indel-data/6837956](url)
but it seems to only contain lib-B datasets for U2OS cells or mESC treated with the three inhibitors. I'm not sure about this file: "PRL_mES_DisLib_Cas9.csv" but maybe that is from the knockout mESC line? (also, there is aparently no replicate paired to this file). 

Would you please consider sharing that dataset as well or point me to it in case it is already present on figshare? 

Thank you! 
Adam

**Comment by maxwshen** [comment]
Hi Adam,

Thanks for bringing this to our attention. I've updated the figshare with two new CSVs, mESC_LibB-Cas9-Tol2-r1 and r2. These can be adjusted using mESC-Dislib-noCas9-Biorep1.csv.

PRL is the knockout mESC line. There is only one replicate for this data, apologies for the messy file naming.

Hope that helps!

Best,
Max

**Comment by krejciadam** [comment]
Nice, thank you!
